### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by toshibochan** [alex224/homebridge-send433#1]
Thanks for sharing your work. Working great!
I have a request.
You can make othe homebridge for receiver 433 signal? I have door and windows wireless sensor, be great I receive notification when the door o window was opened.

**Comment by alex224** [comment]
Hi. No sorry. Sending a signal when a homebridge command comes in is much more simple than always listening for receiving a signal. Next point is that i don't own a window sensor. i don't plan to implement such feature.
